### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by costa85** [costa85/SEBC#3]

**Comment by costa85** [comment]
Access my Cluster metion : installation/labs/MyClusterAccess.md
Cloudera Manager instance URL : http://clouderaseb00.gitcluster.com:7180/cmf/home

**Comment by costa85** [comment]
I'm a finished.

**Comment by mfernest** [comment]
You ended up with 300 splits in your terasort job -- probably a factor in the long duration.

**Comment by mfernest** [comment]
👍
